// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	v1 "github.com/omnipanel/omnipanel/proto/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentInternal_GetSystemInfo_FullMethodName   = "/omnipanel.agent.v1.AgentInternal/GetSystemInfo"
	AgentInternal_GetPluginStatus_FullMethodName = "/omnipanel.agent.v1.AgentInternal/GetPluginStatus"
	AgentInternal_RestartPlugin_FullMethodName   = "/omnipanel.agent.v1.AgentInternal/RestartPlugin"
	AgentInternal_ValidateLicense_FullMethodName = "/omnipanel.agent.v1.AgentInternal/ValidateLicense"
	AgentInternal_ActivateLicense_FullMethodName = "/omnipanel.agent.v1.AgentInternal/ActivateLicense"
)

// AgentInternalClient is the client API for AgentInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentInternal 是 Agent 主进程暴露给 UI 的管理接口
type AgentInternalClient interface {
	GetSystemInfo(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.SystemInfo, error)
	GetPluginStatus(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*PluginStatusList, error)
	RestartPlugin(ctx context.Context, in *RestartPluginRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	ValidateLicense(ctx context.Context, in *LicenseKey, opts ...grpc.CallOption) (*LicenseStatus, error)
	ActivateLicense(ctx context.Context, in *ActivateLicenseRequest, opts ...grpc.CallOption) (*LicenseStatus, error)
}

type agentInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentInternalClient(cc grpc.ClientConnInterface) AgentInternalClient {
	return &agentInternalClient{cc}
}

func (c *agentInternalClient) GetSystemInfo(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.SystemInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.SystemInfo)
	err := c.cc.Invoke(ctx, AgentInternal_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentInternalClient) GetPluginStatus(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*PluginStatusList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginStatusList)
	err := c.cc.Invoke(ctx, AgentInternal_GetPluginStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentInternalClient) RestartPlugin(ctx context.Context, in *RestartPluginRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, AgentInternal_RestartPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentInternalClient) ValidateLicense(ctx context.Context, in *LicenseKey, opts ...grpc.CallOption) (*LicenseStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LicenseStatus)
	err := c.cc.Invoke(ctx, AgentInternal_ValidateLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentInternalClient) ActivateLicense(ctx context.Context, in *ActivateLicenseRequest, opts ...grpc.CallOption) (*LicenseStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LicenseStatus)
	err := c.cc.Invoke(ctx, AgentInternal_ActivateLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentInternalServer is the server API for AgentInternal service.
// All implementations must embed UnimplementedAgentInternalServer
// for forward compatibility.
//
// AgentInternal 是 Agent 主进程暴露给 UI 的管理接口
type AgentInternalServer interface {
	GetSystemInfo(context.Context, *v1.Empty) (*v1.SystemInfo, error)
	GetPluginStatus(context.Context, *v1.Empty) (*PluginStatusList, error)
	RestartPlugin(context.Context, *RestartPluginRequest) (*v1.StatusResponse, error)
	ValidateLicense(context.Context, *LicenseKey) (*LicenseStatus, error)
	ActivateLicense(context.Context, *ActivateLicenseRequest) (*LicenseStatus, error)
	mustEmbedUnimplementedAgentInternalServer()
}

// UnimplementedAgentInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentInternalServer struct{}

func (UnimplementedAgentInternalServer) GetSystemInfo(context.Context, *v1.Empty) (*v1.SystemInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedAgentInternalServer) GetPluginStatus(context.Context, *v1.Empty) (*PluginStatusList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginStatus not implemented")
}
func (UnimplementedAgentInternalServer) RestartPlugin(context.Context, *RestartPluginRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartPlugin not implemented")
}
func (UnimplementedAgentInternalServer) ValidateLicense(context.Context, *LicenseKey) (*LicenseStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateLicense not implemented")
}
func (UnimplementedAgentInternalServer) ActivateLicense(context.Context, *ActivateLicenseRequest) (*LicenseStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateLicense not implemented")
}
func (UnimplementedAgentInternalServer) mustEmbedUnimplementedAgentInternalServer() {}
func (UnimplementedAgentInternalServer) testEmbeddedByValue()                       {}

// UnsafeAgentInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentInternalServer will
// result in compilation errors.
type UnsafeAgentInternalServer interface {
	mustEmbedUnimplementedAgentInternalServer()
}

func RegisterAgentInternalServer(s grpc.ServiceRegistrar, srv AgentInternalServer) {
	// If the following call panics, it indicates UnimplementedAgentInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentInternal_ServiceDesc, srv)
}

func _AgentInternal_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentInternalServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentInternal_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentInternalServer).GetSystemInfo(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentInternal_GetPluginStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentInternalServer).GetPluginStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentInternal_GetPluginStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentInternalServer).GetPluginStatus(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentInternal_RestartPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentInternalServer).RestartPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentInternal_RestartPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentInternalServer).RestartPlugin(ctx, req.(*RestartPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentInternal_ValidateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentInternalServer).ValidateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentInternal_ValidateLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentInternalServer).ValidateLicense(ctx, req.(*LicenseKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentInternal_ActivateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentInternalServer).ActivateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentInternal_ActivateLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentInternalServer).ActivateLicense(ctx, req.(*ActivateLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentInternal_ServiceDesc is the grpc.ServiceDesc for AgentInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omnipanel.agent.v1.AgentInternal",
	HandlerType: (*AgentInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemInfo",
			Handler:    _AgentInternal_GetSystemInfo_Handler,
		},
		{
			MethodName: "GetPluginStatus",
			Handler:    _AgentInternal_GetPluginStatus_Handler,
		},
		{
			MethodName: "RestartPlugin",
			Handler:    _AgentInternal_RestartPlugin_Handler,
		},
		{
			MethodName: "ValidateLicense",
			Handler:    _AgentInternal_ValidateLicense_Handler,
		},
		{
			MethodName: "ActivateLicense",
			Handler:    _AgentInternal_ActivateLicense_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/v1/agent.proto",
}
