// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: agent/v1/agent.proto

package agentv1

import (
	v1 "github.com/omnipanel/omnipanel/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,6,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatus) Reset() {
	*x = PluginStatus{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatus) ProtoMessage() {}

func (x *PluginStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatus.ProtoReflect.Descriptor instead.
func (*PluginStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PluginStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *PluginStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PluginStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *PluginStatus) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type PluginStatusList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginStatus        `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStatusList) Reset() {
	*x = PluginStatusList{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStatusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStatusList) ProtoMessage() {}

func (x *PluginStatusList) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStatusList.ProtoReflect.Descriptor instead.
func (*PluginStatusList) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PluginStatusList) GetPlugins() []*PluginStatus {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type RestartPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartPluginRequest) Reset() {
	*x = RestartPluginRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartPluginRequest) ProtoMessage() {}

func (x *RestartPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartPluginRequest.ProtoReflect.Descriptor instead.
func (*RestartPluginRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RestartPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type LicenseKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseKey) Reset() {
	*x = LicenseKey{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseKey) ProtoMessage() {}

func (x *LicenseKey) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseKey.ProtoReflect.Descriptor instead.
func (*LicenseKey) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *LicenseKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LicenseStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Plan          string                 `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	DaysRemaining int32                  `protobuf:"varint,4,opt,name=days_remaining,json=daysRemaining,proto3" json:"days_remaining,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,5,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Features      []string               `protobuf:"bytes,6,rep,name=features,proto3" json:"features,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseStatus) Reset() {
	*x = LicenseStatus{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseStatus) ProtoMessage() {}

func (x *LicenseStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseStatus.ProtoReflect.Descriptor instead.
func (*LicenseStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *LicenseStatus) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *LicenseStatus) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *LicenseStatus) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *LicenseStatus) GetDaysRemaining() int32 {
	if x != nil {
		return x.DaysRemaining
	}
	return 0
}

func (x *LicenseStatus) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *LicenseStatus) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *LicenseStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActivateLicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateLicenseRequest) Reset() {
	*x = ActivateLicenseRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateLicenseRequest) ProtoMessage() {}

func (x *ActivateLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateLicenseRequest.ProtoReflect.Descriptor instead.
func (*ActivateLicenseRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ActivateLicenseRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ActivateLicenseRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\x12omnipanel.agent.v1\x1a\x16common/v1/common.proto\"\x9d\x01\n" +
	"\fPluginStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\x12\x1b\n" +
	"\tmemory_mb\x18\x06 \x01(\x04R\bmemoryMb\"N\n" +
	"\x10PluginStatusList\x12:\n" +
	"\aplugins\x18\x01 \x03(\v2 .omnipanel.agent.v1.PluginStatusR\aplugins\"7\n" +
	"\x14RestartPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\"\x1e\n" +
	"\n" +
	"LicenseKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xd7\x01\n" +
	"\rLicenseStatus\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x12\n" +
	"\x04plan\x18\x02 \x01(\tR\x04plan\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12%\n" +
	"\x0edays_remaining\x18\x04 \x01(\x05R\rdaysRemaining\x12 \n" +
	"\vfingerprint\x18\x05 \x01(\tR\vfingerprint\x12\x1a\n" +
	"\bfeatures\x18\x06 \x03(\tR\bfeatures\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"@\n" +
	"\x16ActivateLicenseRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2\xca\x03\n" +
	"\rAgentInternal\x12L\n" +
	"\rGetSystemInfo\x12\x1a.omnipanel.common.v1.Empty\x1a\x1f.omnipanel.common.v1.SystemInfo\x12S\n" +
	"\x0fGetPluginStatus\x12\x1a.omnipanel.common.v1.Empty\x1a$.omnipanel.agent.v1.PluginStatusList\x12^\n" +
	"\rRestartPlugin\x12(.omnipanel.agent.v1.RestartPluginRequest\x1a#.omnipanel.common.v1.StatusResponse\x12T\n" +
	"\x0fValidateLicense\x12\x1e.omnipanel.agent.v1.LicenseKey\x1a!.omnipanel.agent.v1.LicenseStatus\x12`\n" +
	"\x0fActivateLicense\x12*.omnipanel.agent.v1.ActivateLicenseRequest\x1a!.omnipanel.agent.v1.LicenseStatusB7Z5github.com/omnipanel/omnipanel/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_v1_agent_proto_goTypes = []any{
	(*PluginStatus)(nil),           // 0: omnipanel.agent.v1.PluginStatus
	(*PluginStatusList)(nil),       // 1: omnipanel.agent.v1.PluginStatusList
	(*RestartPluginRequest)(nil),   // 2: omnipanel.agent.v1.RestartPluginRequest
	(*LicenseKey)(nil),             // 3: omnipanel.agent.v1.LicenseKey
	(*LicenseStatus)(nil),          // 4: omnipanel.agent.v1.LicenseStatus
	(*ActivateLicenseRequest)(nil), // 5: omnipanel.agent.v1.ActivateLicenseRequest
	(*v1.Empty)(nil),               // 6: omnipanel.common.v1.Empty
	(*v1.SystemInfo)(nil),          // 7: omnipanel.common.v1.SystemInfo
	(*v1.StatusResponse)(nil),      // 8: omnipanel.common.v1.StatusResponse
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	0, // 0: omnipanel.agent.v1.PluginStatusList.plugins:type_name -> omnipanel.agent.v1.PluginStatus
	6, // 1: omnipanel.agent.v1.AgentInternal.GetSystemInfo:input_type -> omnipanel.common.v1.Empty
	6, // 2: omnipanel.agent.v1.AgentInternal.GetPluginStatus:input_type -> omnipanel.common.v1.Empty
	2, // 3: omnipanel.agent.v1.AgentInternal.RestartPlugin:input_type -> omnipanel.agent.v1.RestartPluginRequest
	3, // 4: omnipanel.agent.v1.AgentInternal.ValidateLicense:input_type -> omnipanel.agent.v1.LicenseKey
	5, // 5: omnipanel.agent.v1.AgentInternal.ActivateLicense:input_type -> omnipanel.agent.v1.ActivateLicenseRequest
	7, // 6: omnipanel.agent.v1.AgentInternal.GetSystemInfo:output_type -> omnipanel.common.v1.SystemInfo
	1, // 7: omnipanel.agent.v1.AgentInternal.GetPluginStatus:output_type -> omnipanel.agent.v1.PluginStatusList
	8, // 8: omnipanel.agent.v1.AgentInternal.RestartPlugin:output_type -> omnipanel.common.v1.StatusResponse
	4, // 9: omnipanel.agent.v1.AgentInternal.ValidateLicense:output_type -> omnipanel.agent.v1.LicenseStatus
	4, // 10: omnipanel.agent.v1.AgentInternal.ActivateLicense:output_type -> omnipanel.agent.v1.LicenseStatus
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
