// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: sdt/v1/sdt.proto

package sdtv1

import (
	v1 "github.com/omnipanel/omnipanel/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallServerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstallDir     string                 `protobuf:"bytes,1,opt,name=install_dir,json=installDir,proto3" json:"install_dir,omitempty"`
	SteamUsername  string                 `protobuf:"bytes,2,opt,name=steam_username,json=steamUsername,proto3" json:"steam_username,omitempty"`
	SteamPassword  string                 `protobuf:"bytes,3,opt,name=steam_password,json=steamPassword,proto3" json:"steam_password,omitempty"`
	ForceReinstall bool                   `protobuf:"varint,4,opt,name=force_reinstall,json=forceReinstall,proto3" json:"force_reinstall,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstallServerRequest) Reset() {
	*x = InstallServerRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallServerRequest) ProtoMessage() {}

func (x *InstallServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallServerRequest.ProtoReflect.Descriptor instead.
func (*InstallServerRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{0}
}

func (x *InstallServerRequest) GetInstallDir() string {
	if x != nil {
		return x.InstallDir
	}
	return ""
}

func (x *InstallServerRequest) GetSteamUsername() string {
	if x != nil {
		return x.SteamUsername
	}
	return ""
}

func (x *InstallServerRequest) GetSteamPassword() string {
	if x != nil {
		return x.SteamPassword
	}
	return ""
}

func (x *InstallServerRequest) GetForceReinstall() bool {
	if x != nil {
		return x.ForceReinstall
	}
	return false
}

type ServerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Installed     bool                   `protobuf:"varint,1,opt,name=installed,proto3" json:"installed,omitempty"`
	Running       bool                   `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	OnlinePlayers int32                  `protobuf:"varint,5,opt,name=online_players,json=onlinePlayers,proto3" json:"online_players,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,6,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Tps           float64                `protobuf:"fixed64,7,opt,name=tps,proto3" json:"tps,omitempty"`
	Fps           int32                  `protobuf:"varint,8,opt,name=fps,proto3" json:"fps,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,9,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Uptime        string                 `protobuf:"bytes,10,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusResponse) Reset() {
	*x = ServerStatusResponse{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusResponse) ProtoMessage() {}

func (x *ServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusResponse.ProtoReflect.Descriptor instead.
func (*ServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStatusResponse) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *ServerStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ServerStatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ServerStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerStatusResponse) GetOnlinePlayers() int32 {
	if x != nil {
		return x.OnlinePlayers
	}
	return 0
}

func (x *ServerStatusResponse) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *ServerStatusResponse) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *ServerStatusResponse) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *ServerStatusResponse) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ServerStatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type ServerConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServerName           string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerDescription    string                 `protobuf:"bytes,2,opt,name=server_description,json=serverDescription,proto3" json:"server_description,omitempty"`
	ServerPassword       string                 `protobuf:"bytes,3,opt,name=server_password,json=serverPassword,proto3" json:"server_password,omitempty"`
	ServerMaxPlayerCount int32                  `protobuf:"varint,4,opt,name=server_max_player_count,json=serverMaxPlayerCount,proto3" json:"server_max_player_count,omitempty"`
	ServerPort           int32                  `protobuf:"varint,5,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	ServerVisibility     int32                  `protobuf:"varint,6,opt,name=server_visibility,json=serverVisibility,proto3" json:"server_visibility,omitempty"`
	GameDifficulty       int32                  `protobuf:"varint,7,opt,name=game_difficulty,json=gameDifficulty,proto3" json:"game_difficulty,omitempty"`
	GameMode             string                 `protobuf:"bytes,8,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	WorldGenSeed         string                 `protobuf:"bytes,9,opt,name=world_gen_seed,json=worldGenSeed,proto3" json:"world_gen_seed,omitempty"`
	WorldGenSize         int32                  `protobuf:"varint,10,opt,name=world_gen_size,json=worldGenSize,proto3" json:"world_gen_size,omitempty"`
	DayNightLength       int32                  `protobuf:"varint,11,opt,name=day_night_length,json=dayNightLength,proto3" json:"day_night_length,omitempty"`
	MaxSpawnedZombies    int32                  `protobuf:"varint,12,opt,name=max_spawned_zombies,json=maxSpawnedZombies,proto3" json:"max_spawned_zombies,omitempty"`
	MaxSpawnedAnimals    int32                  `protobuf:"varint,13,opt,name=max_spawned_animals,json=maxSpawnedAnimals,proto3" json:"max_spawned_animals,omitempty"`
	EacEnabled           bool                   `protobuf:"varint,14,opt,name=eac_enabled,json=eacEnabled,proto3" json:"eac_enabled,omitempty"`
	BloodMoonFrequency   int32                  `protobuf:"varint,15,opt,name=blood_moon_frequency,json=bloodMoonFrequency,proto3" json:"blood_moon_frequency,omitempty"`
	AirDropFrequency     int32                  `protobuf:"varint,16,opt,name=air_drop_frequency,json=airDropFrequency,proto3" json:"air_drop_frequency,omitempty"`
	DropOnDeath          int32                  `protobuf:"varint,17,opt,name=drop_on_death,json=dropOnDeath,proto3" json:"drop_on_death,omitempty"`
	DropOnQuit           int32                  `protobuf:"varint,18,opt,name=drop_on_quit,json=dropOnQuit,proto3" json:"drop_on_quit,omitempty"`
	TelnetEnabled        bool                   `protobuf:"varint,19,opt,name=telnet_enabled,json=telnetEnabled,proto3" json:"telnet_enabled,omitempty"`
	TelnetPort           int32                  `protobuf:"varint,20,opt,name=telnet_port,json=telnetPort,proto3" json:"telnet_port,omitempty"`
	TelnetPassword       string                 `protobuf:"bytes,21,opt,name=telnet_password,json=telnetPassword,proto3" json:"telnet_password,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{2}
}

func (x *ServerConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerConfig) GetServerDescription() string {
	if x != nil {
		return x.ServerDescription
	}
	return ""
}

func (x *ServerConfig) GetServerPassword() string {
	if x != nil {
		return x.ServerPassword
	}
	return ""
}

func (x *ServerConfig) GetServerMaxPlayerCount() int32 {
	if x != nil {
		return x.ServerMaxPlayerCount
	}
	return 0
}

func (x *ServerConfig) GetServerPort() int32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *ServerConfig) GetServerVisibility() int32 {
	if x != nil {
		return x.ServerVisibility
	}
	return 0
}

func (x *ServerConfig) GetGameDifficulty() int32 {
	if x != nil {
		return x.GameDifficulty
	}
	return 0
}

func (x *ServerConfig) GetGameMode() string {
	if x != nil {
		return x.GameMode
	}
	return ""
}

func (x *ServerConfig) GetWorldGenSeed() string {
	if x != nil {
		return x.WorldGenSeed
	}
	return ""
}

func (x *ServerConfig) GetWorldGenSize() int32 {
	if x != nil {
		return x.WorldGenSize
	}
	return 0
}

func (x *ServerConfig) GetDayNightLength() int32 {
	if x != nil {
		return x.DayNightLength
	}
	return 0
}

func (x *ServerConfig) GetMaxSpawnedZombies() int32 {
	if x != nil {
		return x.MaxSpawnedZombies
	}
	return 0
}

func (x *ServerConfig) GetMaxSpawnedAnimals() int32 {
	if x != nil {
		return x.MaxSpawnedAnimals
	}
	return 0
}

func (x *ServerConfig) GetEacEnabled() bool {
	if x != nil {
		return x.EacEnabled
	}
	return false
}

func (x *ServerConfig) GetBloodMoonFrequency() int32 {
	if x != nil {
		return x.BloodMoonFrequency
	}
	return 0
}

func (x *ServerConfig) GetAirDropFrequency() int32 {
	if x != nil {
		return x.AirDropFrequency
	}
	return 0
}

func (x *ServerConfig) GetDropOnDeath() int32 {
	if x != nil {
		return x.DropOnDeath
	}
	return 0
}

func (x *ServerConfig) GetDropOnQuit() int32 {
	if x != nil {
		return x.DropOnQuit
	}
	return 0
}

func (x *ServerConfig) GetTelnetEnabled() bool {
	if x != nil {
		return x.TelnetEnabled
	}
	return false
}

func (x *ServerConfig) GetTelnetPort() int32 {
	if x != nil {
		return x.TelnetPort
	}
	return 0
}

func (x *ServerConfig) GetTelnetPassword() string {
	if x != nil {
		return x.TelnetPassword
	}
	return ""
}

type UpdateServerConfigRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Config           *ServerConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ApplyImmediately bool                   `protobuf:"varint,2,opt,name=apply_immediately,json=applyImmediately,proto3" json:"apply_immediately,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateServerConfigRequest) Reset() {
	*x = UpdateServerConfigRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerConfigRequest) ProtoMessage() {}

func (x *UpdateServerConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerConfigRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateServerConfigRequest) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateServerConfigRequest) GetApplyImmediately() bool {
	if x != nil {
		return x.ApplyImmediately
	}
	return false
}

type ConsoleCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleCommandRequest) Reset() {
	*x = ConsoleCommandRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCommandRequest) ProtoMessage() {}

func (x *ConsoleCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCommandRequest.ProtoReflect.Descriptor instead.
func (*ConsoleCommandRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{4}
}

func (x *ConsoleCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ConsoleCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleCommandResponse) Reset() {
	*x = ConsoleCommandResponse{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleCommandResponse) ProtoMessage() {}

func (x *ConsoleCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleCommandResponse.ProtoReflect.Descriptor instead.
func (*ConsoleCommandResponse) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{5}
}

func (x *ConsoleCommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ConsoleCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConsoleLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleLine) Reset() {
	*x = ConsoleLine{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleLine) ProtoMessage() {}

func (x *ConsoleLine) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleLine.ProtoReflect.Descriptor instead.
func (*ConsoleLine) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{6}
}

func (x *ConsoleLine) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ConsoleLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ConsoleLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SteamId       string                 `protobuf:"bytes,2,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	PlayTime      string                 `protobuf:"bytes,3,opt,name=play_time,json=playTime,proto3" json:"play_time,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	Online        bool                   `protobuf:"varint,6,opt,name=online,proto3" json:"online,omitempty"`
	Banned        bool                   `protobuf:"varint,7,opt,name=banned,proto3" json:"banned,omitempty"`
	IpAddress     string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{7}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *Player) GetPlayTime() string {
	if x != nil {
		return x.PlayTime
	}
	return ""
}

func (x *Player) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Player) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Player) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Player) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *Player) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type PlayerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerList) Reset() {
	*x = PlayerList{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerList) ProtoMessage() {}

func (x *PlayerList) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerList.ProtoReflect.Descriptor instead.
func (*PlayerList) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerList) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type KickPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       string                 `protobuf:"bytes,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerRequest) Reset() {
	*x = KickPlayerRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRequest) ProtoMessage() {}

func (x *KickPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRequest.ProtoReflect.Descriptor instead.
func (*KickPlayerRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{9}
}

func (x *KickPlayerRequest) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *KickPlayerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       string                 `protobuf:"bytes,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DurationHours int32                  `protobuf:"varint,3,opt,name=duration_hours,json=durationHours,proto3" json:"duration_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanPlayerRequest) Reset() {
	*x = BanPlayerRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPlayerRequest) ProtoMessage() {}

func (x *BanPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPlayerRequest.ProtoReflect.Descriptor instead.
func (*BanPlayerRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{10}
}

func (x *BanPlayerRequest) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *BanPlayerRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BanPlayerRequest) GetDurationHours() int32 {
	if x != nil {
		return x.DurationHours
	}
	return 0
}

type UnbanPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       string                 `protobuf:"bytes,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanPlayerRequest) Reset() {
	*x = UnbanPlayerRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPlayerRequest) ProtoMessage() {}

func (x *UnbanPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPlayerRequest.ProtoReflect.Descriptor instead.
func (*UnbanPlayerRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{11}
}

func (x *UnbanPlayerRequest) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

type TeleportPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       string                 `protobuf:"bytes,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeleportPlayerRequest) Reset() {
	*x = TeleportPlayerRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeleportPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeleportPlayerRequest) ProtoMessage() {}

func (x *TeleportPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeleportPlayerRequest.ProtoReflect.Descriptor instead.
func (*TeleportPlayerRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{12}
}

func (x *TeleportPlayerRequest) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *TeleportPlayerRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TeleportPlayerRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TeleportPlayerRequest) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type GiveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       string                 `protobuf:"bytes,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Quality       int32                  `protobuf:"varint,4,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveItemRequest) Reset() {
	*x = GiveItemRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveItemRequest) ProtoMessage() {}

func (x *GiveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveItemRequest.ProtoReflect.Descriptor instead.
func (*GiveItemRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{13}
}

func (x *GiveItemRequest) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *GiveItemRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *GiveItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GiveItemRequest) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

type WhitelistEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       string                 `protobuf:"bytes,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistEntry) Reset() {
	*x = WhitelistEntry{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistEntry) ProtoMessage() {}

func (x *WhitelistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistEntry.ProtoReflect.Descriptor instead.
func (*WhitelistEntry) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{14}
}

func (x *WhitelistEntry) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *WhitelistEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Entries       []*WhitelistEntry      `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistResponse) Reset() {
	*x = WhitelistResponse{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistResponse) ProtoMessage() {}

func (x *WhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistResponse.ProtoReflect.Descriptor instead.
func (*WhitelistResponse) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{15}
}

func (x *WhitelistResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WhitelistResponse) GetEntries() []*WhitelistEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AdminEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SteamId         string                 `protobuf:"bytes,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	PermissionLevel int32                  `protobuf:"varint,2,opt,name=permission_level,json=permissionLevel,proto3" json:"permission_level,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminEntry) Reset() {
	*x = AdminEntry{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminEntry) ProtoMessage() {}

func (x *AdminEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminEntry.ProtoReflect.Descriptor instead.
func (*AdminEntry) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{16}
}

func (x *AdminEntry) GetSteamId() string {
	if x != nil {
		return x.SteamId
	}
	return ""
}

func (x *AdminEntry) GetPermissionLevel() int32 {
	if x != nil {
		return x.PermissionLevel
	}
	return 0
}

func (x *AdminEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AdminList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*AdminEntry          `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminList) Reset() {
	*x = AdminList{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminList) ProtoMessage() {}

func (x *AdminList) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminList.ProtoReflect.Descriptor instead.
func (*AdminList) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{17}
}

func (x *AdminList) GetAdmins() []*AdminEntry {
	if x != nil {
		return x.Admins
	}
	return nil
}

type ValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{18}
}

func (x *ValidationResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidationResult) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type BackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupResponse) Reset() {
	*x = BackupResponse{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupResponse) ProtoMessage() {}

func (x *BackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupResponse.ProtoReflect.Descriptor instead.
func (*BackupResponse) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{19}
}

func (x *BackupResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *BackupResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type BackupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backups       []*BackupResponse      `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupList) Reset() {
	*x = BackupList{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupList) ProtoMessage() {}

func (x *BackupList) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupList.ProtoReflect.Descriptor instead.
func (*BackupList) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{20}
}

func (x *BackupList) GetBackups() []*BackupResponse {
	if x != nil {
		return x.Backups
	}
	return nil
}

type RestoreBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupId      string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupRequest) Reset() {
	*x = RestoreBackupRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupRequest) ProtoMessage() {}

func (x *RestoreBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{21}
}

func (x *RestoreBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

type DeleteBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupId      string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId,proto3" json:"backup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteBackupRequest) GetBackupId() string {
	if x != nil {
		return x.BackupId
	}
	return ""
}

type ModInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModInfo) Reset() {
	*x = ModInfo{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModInfo) ProtoMessage() {}

func (x *ModInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModInfo.ProtoReflect.Descriptor instead.
func (*ModInfo) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{23}
}

func (x *ModInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ModInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ModInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ModList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mods          []*ModInfo             `protobuf:"bytes,1,rep,name=mods,proto3" json:"mods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModList) Reset() {
	*x = ModList{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModList) ProtoMessage() {}

func (x *ModList) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModList.ProtoReflect.Descriptor instead.
func (*ModList) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{24}
}

func (x *ModList) GetMods() []*ModInfo {
	if x != nil {
		return x.Mods
	}
	return nil
}

type InstallModRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	ModName       string                 `protobuf:"bytes,2,opt,name=mod_name,json=modName,proto3" json:"mod_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallModRequest) Reset() {
	*x = InstallModRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallModRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallModRequest) ProtoMessage() {}

func (x *InstallModRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallModRequest.ProtoReflect.Descriptor instead.
func (*InstallModRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{25}
}

func (x *InstallModRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *InstallModRequest) GetModName() string {
	if x != nil {
		return x.ModName
	}
	return ""
}

type RemoveModRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModName       string                 `protobuf:"bytes,1,opt,name=mod_name,json=modName,proto3" json:"mod_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveModRequest) Reset() {
	*x = RemoveModRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveModRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveModRequest) ProtoMessage() {}

func (x *RemoveModRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveModRequest.ProtoReflect.Descriptor instead.
func (*RemoveModRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveModRequest) GetModName() string {
	if x != nil {
		return x.ModName
	}
	return ""
}

type ToggleModRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModName       string                 `protobuf:"bytes,1,opt,name=mod_name,json=modName,proto3" json:"mod_name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleModRequest) Reset() {
	*x = ToggleModRequest{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleModRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleModRequest) ProtoMessage() {}

func (x *ToggleModRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleModRequest.ProtoReflect.Descriptor instead.
func (*ToggleModRequest) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{27}
}

func (x *ToggleModRequest) GetModName() string {
	if x != nil {
		return x.ModName
	}
	return ""
}

func (x *ToggleModRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ServerMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tps             float64                `protobuf:"fixed64,1,opt,name=tps,proto3" json:"tps,omitempty"`
	Fps             int32                  `protobuf:"varint,2,opt,name=fps,proto3" json:"fps,omitempty"`
	OnlinePlayers   int32                  `protobuf:"varint,3,opt,name=online_players,json=onlinePlayers,proto3" json:"online_players,omitempty"`
	MemoryUsedMb    uint64                 `protobuf:"varint,4,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	CpuPercent      float64                `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	NetworkInBytes  int64                  `protobuf:"varint,6,opt,name=network_in_bytes,json=networkInBytes,proto3" json:"network_in_bytes,omitempty"`
	NetworkOutBytes int64                  `protobuf:"varint,7,opt,name=network_out_bytes,json=networkOutBytes,proto3" json:"network_out_bytes,omitempty"`
	Timestamp       string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerMetrics) Reset() {
	*x = ServerMetrics{}
	mi := &file_sdt_v1_sdt_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetrics) ProtoMessage() {}

func (x *ServerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_sdt_v1_sdt_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetrics.ProtoReflect.Descriptor instead.
func (*ServerMetrics) Descriptor() ([]byte, []int) {
	return file_sdt_v1_sdt_proto_rawDescGZIP(), []int{28}
}

func (x *ServerMetrics) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *ServerMetrics) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *ServerMetrics) GetOnlinePlayers() int32 {
	if x != nil {
		return x.OnlinePlayers
	}
	return 0
}

func (x *ServerMetrics) GetMemoryUsedMb() uint64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *ServerMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ServerMetrics) GetNetworkInBytes() int64 {
	if x != nil {
		return x.NetworkInBytes
	}
	return 0
}

func (x *ServerMetrics) GetNetworkOutBytes() int64 {
	if x != nil {
		return x.NetworkOutBytes
	}
	return 0
}

func (x *ServerMetrics) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_sdt_v1_sdt_proto protoreflect.FileDescriptor

const file_sdt_v1_sdt_proto_rawDesc = "" +
	"\n" +
	"\x10sdt/v1/sdt.proto\x12\x10omnipanel.sdt.v1\x1a\x16common/v1/common.proto\"\xae\x01\n" +
	"\x14InstallServerRequest\x12\x1f\n" +
	"\vinstall_dir\x18\x01 \x01(\tR\n" +
	"installDir\x12%\n" +
	"\x0esteam_username\x18\x02 \x01(\tR\rsteamUsername\x12%\n" +
	"\x0esteam_password\x18\x03 \x01(\tR\rsteamPassword\x12'\n" +
	"\x0fforce_reinstall\x18\x04 \x01(\bR\x0eforceReinstall\"\x9b\x02\n" +
	"\x14ServerStatusResponse\x12\x1c\n" +
	"\tinstalled\x18\x01 \x01(\bR\tinstalled\x12\x18\n" +
	"\arunning\x18\x02 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12%\n" +
	"\x0eonline_players\x18\x05 \x01(\x05R\ronlinePlayers\x12\x1f\n" +
	"\vmax_players\x18\x06 \x01(\x05R\n" +
	"maxPlayers\x12\x10\n" +
	"\x03tps\x18\a \x01(\x01R\x03tps\x12\x10\n" +
	"\x03fps\x18\b \x01(\x05R\x03fps\x12\x1b\n" +
	"\tmemory_mb\x18\t \x01(\x04R\bmemoryMb\x12\x16\n" +
	"\x06uptime\x18\n" +
	" \x01(\tR\x06uptime\"\xe0\x06\n" +
	"\fServerConfig\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12-\n" +
	"\x12server_description\x18\x02 \x01(\tR\x11serverDescription\x12'\n" +
	"\x0fserver_password\x18\x03 \x01(\tR\x0eserverPassword\x125\n" +
	"\x17server_max_player_count\x18\x04 \x01(\x05R\x14serverMaxPlayerCount\x12\x1f\n" +
	"\vserver_port\x18\x05 \x01(\x05R\n" +
	"serverPort\x12+\n" +
	"\x11server_visibility\x18\x06 \x01(\x05R\x10serverVisibility\x12'\n" +
	"\x0fgame_difficulty\x18\a \x01(\x05R\x0egameDifficulty\x12\x1b\n" +
	"\tgame_mode\x18\b \x01(\tR\bgameMode\x12$\n" +
	"\x0eworld_gen_seed\x18\t \x01(\tR\fworldGenSeed\x12$\n" +
	"\x0eworld_gen_size\x18\n" +
	" \x01(\x05R\fworldGenSize\x12(\n" +
	"\x10day_night_length\x18\v \x01(\x05R\x0edayNightLength\x12.\n" +
	"\x13max_spawned_zombies\x18\f \x01(\x05R\x11maxSpawnedZombies\x12.\n" +
	"\x13max_spawned_animals\x18\r \x01(\x05R\x11maxSpawnedAnimals\x12\x1f\n" +
	"\veac_enabled\x18\x0e \x01(\bR\n" +
	"eacEnabled\x120\n" +
	"\x14blood_moon_frequency\x18\x0f \x01(\x05R\x12bloodMoonFrequency\x12,\n" +
	"\x12air_drop_frequency\x18\x10 \x01(\x05R\x10airDropFrequency\x12\"\n" +
	"\rdrop_on_death\x18\x11 \x01(\x05R\vdropOnDeath\x12 \n" +
	"\fdrop_on_quit\x18\x12 \x01(\x05R\n" +
	"dropOnQuit\x12%\n" +
	"\x0etelnet_enabled\x18\x13 \x01(\bR\rtelnetEnabled\x12\x1f\n" +
	"\vtelnet_port\x18\x14 \x01(\x05R\n" +
	"telnetPort\x12'\n" +
	"\x0ftelnet_password\x18\x15 \x01(\tR\x0etelnetPassword\"\x80\x01\n" +
	"\x19UpdateServerConfigRequest\x126\n" +
	"\x06config\x18\x01 \x01(\v2\x1e.omnipanel.sdt.v1.ServerConfigR\x06config\x12+\n" +
	"\x11apply_immediately\x18\x02 \x01(\bR\x10applyImmediately\"1\n" +
	"\x15ConsoleCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"J\n" +
	"\x16ConsoleCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"[\n" +
	"\vConsoleLine\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xcf\x01\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bsteam_id\x18\x02 \x01(\tR\asteamId\x12\x1b\n" +
	"\tplay_time\x18\x03 \x01(\tR\bplayTime\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12\x16\n" +
	"\x06online\x18\x06 \x01(\bR\x06online\x12\x16\n" +
	"\x06banned\x18\a \x01(\bR\x06banned\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\"@\n" +
	"\n" +
	"PlayerList\x122\n" +
	"\aplayers\x18\x01 \x03(\v2\x18.omnipanel.sdt.v1.PlayerR\aplayers\"F\n" +
	"\x11KickPlayerRequest\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\tR\asteamId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"l\n" +
	"\x10BanPlayerRequest\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\tR\asteamId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0eduration_hours\x18\x03 \x01(\x05R\rdurationHours\"/\n" +
	"\x12UnbanPlayerRequest\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\tR\asteamId\"\\\n" +
	"\x15TeleportPlayerRequest\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\tR\asteamId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x01R\x01z\"\x7f\n" +
	"\x0fGiveItemRequest\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\tR\asteamId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x18\n" +
	"\aquality\x18\x04 \x01(\x05R\aquality\"?\n" +
	"\x0eWhitelistEntry\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\tR\asteamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"i\n" +
	"\x11WhitelistResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12:\n" +
	"\aentries\x18\x02 \x03(\v2 .omnipanel.sdt.v1.WhitelistEntryR\aentries\"f\n" +
	"\n" +
	"AdminEntry\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\tR\asteamId\x12)\n" +
	"\x10permission_level\x18\x02 \x01(\x05R\x0fpermissionLevel\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"A\n" +
	"\tAdminList\x124\n" +
	"\x06admins\x18\x01 \x03(\v2\x1c.omnipanel.sdt.v1.AdminEntryR\x06admins\"\\\n" +
	"\x10ValidationResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"g\n" +
	"\x0eBackupResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"H\n" +
	"\n" +
	"BackupList\x12:\n" +
	"\abackups\x18\x01 \x03(\v2 .omnipanel.sdt.v1.BackupResponseR\abackups\"3\n" +
	"\x14RestoreBackupRequest\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\"2\n" +
	"\x13DeleteBackupRequest\x12\x1b\n" +
	"\tbackup_id\x18\x01 \x01(\tR\bbackupId\"}\n" +
	"\aModInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"8\n" +
	"\aModList\x12-\n" +
	"\x04mods\x18\x01 \x03(\v2\x19.omnipanel.sdt.v1.ModInfoR\x04mods\"O\n" +
	"\x11InstallModRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12\x19\n" +
	"\bmod_name\x18\x02 \x01(\tR\amodName\"-\n" +
	"\x10RemoveModRequest\x12\x19\n" +
	"\bmod_name\x18\x01 \x01(\tR\amodName\"G\n" +
	"\x10ToggleModRequest\x12\x19\n" +
	"\bmod_name\x18\x01 \x01(\tR\amodName\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\x95\x02\n" +
	"\rServerMetrics\x12\x10\n" +
	"\x03tps\x18\x01 \x01(\x01R\x03tps\x12\x10\n" +
	"\x03fps\x18\x02 \x01(\x05R\x03fps\x12%\n" +
	"\x0eonline_players\x18\x03 \x01(\x05R\ronlinePlayers\x12$\n" +
	"\x0ememory_used_mb\x18\x04 \x01(\x04R\fmemoryUsedMb\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12(\n" +
	"\x10network_in_bytes\x18\x06 \x01(\x03R\x0enetworkInBytes\x12*\n" +
	"\x11network_out_bytes\x18\a \x01(\x03R\x0fnetworkOutBytes\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp2\xd6\x14\n" +
	"\n" +
	"SDTService\x12X\n" +
	"\rInstallServer\x12&.omnipanel.sdt.v1.InstallServerRequest\x1a\x1d.omnipanel.common.v1.LogEntry0\x01\x12N\n" +
	"\vStartServer\x12\x1a.omnipanel.common.v1.Empty\x1a#.omnipanel.common.v1.StatusResponse\x12M\n" +
	"\n" +
	"StopServer\x12\x1a.omnipanel.common.v1.Empty\x1a#.omnipanel.common.v1.StatusResponse\x12P\n" +
	"\rRestartServer\x12\x1a.omnipanel.common.v1.Empty\x1a#.omnipanel.common.v1.StatusResponse\x12U\n" +
	"\x0fGetServerStatus\x12\x1a.omnipanel.common.v1.Empty\x1a&.omnipanel.sdt.v1.ServerStatusResponse\x12g\n" +
	"\x12SendConsoleCommand\x12'.omnipanel.sdt.v1.ConsoleCommandRequest\x1a(.omnipanel.sdt.v1.ConsoleCommandResponse\x12T\n" +
	"\rStreamConsole\x12\".omnipanel.common.v1.StreamRequest\x1a\x1d.omnipanel.sdt.v1.ConsoleLine0\x01\x12M\n" +
	"\x0fGetServerConfig\x12\x1a.omnipanel.common.v1.Empty\x1a\x1e.omnipanel.sdt.v1.ServerConfig\x12f\n" +
	"\x12UpdateServerConfig\x12+.omnipanel.sdt.v1.UpdateServerConfigRequest\x1a#.omnipanel.common.v1.StatusResponse\x12P\n" +
	"\x0eValidateConfig\x12\x1a.omnipanel.common.v1.Empty\x1a\".omnipanel.sdt.v1.ValidationResult\x12G\n" +
	"\vListPlayers\x12\x1a.omnipanel.common.v1.Empty\x1a\x1c.omnipanel.sdt.v1.PlayerList\x12V\n" +
	"\n" +
	"KickPlayer\x12#.omnipanel.sdt.v1.KickPlayerRequest\x1a#.omnipanel.common.v1.StatusResponse\x12T\n" +
	"\tBanPlayer\x12\".omnipanel.sdt.v1.BanPlayerRequest\x1a#.omnipanel.common.v1.StatusResponse\x12X\n" +
	"\vUnbanPlayer\x12$.omnipanel.sdt.v1.UnbanPlayerRequest\x1a#.omnipanel.common.v1.StatusResponse\x12^\n" +
	"\x0eTeleportPlayer\x12'.omnipanel.sdt.v1.TeleportPlayerRequest\x1a#.omnipanel.common.v1.StatusResponse\x12R\n" +
	"\bGiveItem\x12!.omnipanel.sdt.v1.GiveItemRequest\x1a#.omnipanel.common.v1.StatusResponse\x12P\n" +
	"\rListWhitelist\x12\x1a.omnipanel.common.v1.Empty\x1a#.omnipanel.sdt.v1.WhitelistResponse\x12U\n" +
	"\fAddWhitelist\x12 .omnipanel.sdt.v1.WhitelistEntry\x1a#.omnipanel.common.v1.StatusResponse\x12X\n" +
	"\x0fRemoveWhitelist\x12 .omnipanel.sdt.v1.WhitelistEntry\x1a#.omnipanel.common.v1.StatusResponse\x12E\n" +
	"\n" +
	"ListAdmins\x12\x1a.omnipanel.common.v1.Empty\x1a\x1b.omnipanel.sdt.v1.AdminList\x12M\n" +
	"\bAddAdmin\x12\x1c.omnipanel.sdt.v1.AdminEntry\x1a#.omnipanel.common.v1.StatusResponse\x12P\n" +
	"\vRemoveAdmin\x12\x1c.omnipanel.sdt.v1.AdminEntry\x1a#.omnipanel.common.v1.StatusResponse\x12L\n" +
	"\fCreateBackup\x12\x1a.omnipanel.common.v1.Empty\x1a .omnipanel.sdt.v1.BackupResponse\x12G\n" +
	"\vListBackups\x12\x1a.omnipanel.common.v1.Empty\x1a\x1c.omnipanel.sdt.v1.BackupList\x12\\\n" +
	"\rRestoreBackup\x12&.omnipanel.sdt.v1.RestoreBackupRequest\x1a#.omnipanel.common.v1.StatusResponse\x12Z\n" +
	"\fDeleteBackup\x12%.omnipanel.sdt.v1.DeleteBackupRequest\x1a#.omnipanel.common.v1.StatusResponse\x12A\n" +
	"\bListMods\x12\x1a.omnipanel.common.v1.Empty\x1a\x19.omnipanel.sdt.v1.ModList\x12V\n" +
	"\n" +
	"InstallMod\x12#.omnipanel.sdt.v1.InstallModRequest\x1a#.omnipanel.common.v1.StatusResponse\x12T\n" +
	"\tRemoveMod\x12\".omnipanel.sdt.v1.RemoveModRequest\x1a#.omnipanel.common.v1.StatusResponse\x12T\n" +
	"\tToggleMod\x12\".omnipanel.sdt.v1.ToggleModRequest\x1a#.omnipanel.common.v1.StatusResponse\x12V\n" +
	"\rStreamMetrics\x12\".omnipanel.common.v1.StreamRequest\x1a\x1f.omnipanel.sdt.v1.ServerMetrics0\x01B3Z1github.com/omnipanel/omnipanel/proto/sdt/v1;sdtv1b\x06proto3"

var (
	file_sdt_v1_sdt_proto_rawDescOnce sync.Once
	file_sdt_v1_sdt_proto_rawDescData []byte
)

func file_sdt_v1_sdt_proto_rawDescGZIP() []byte {
	file_sdt_v1_sdt_proto_rawDescOnce.Do(func() {
		file_sdt_v1_sdt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdt_v1_sdt_proto_rawDesc), len(file_sdt_v1_sdt_proto_rawDesc)))
	})
	return file_sdt_v1_sdt_proto_rawDescData
}

var file_sdt_v1_sdt_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_sdt_v1_sdt_proto_goTypes = []any{
	(*InstallServerRequest)(nil),      // 0: omnipanel.sdt.v1.InstallServerRequest
	(*ServerStatusResponse)(nil),      // 1: omnipanel.sdt.v1.ServerStatusResponse
	(*ServerConfig)(nil),              // 2: omnipanel.sdt.v1.ServerConfig
	(*UpdateServerConfigRequest)(nil), // 3: omnipanel.sdt.v1.UpdateServerConfigRequest
	(*ConsoleCommandRequest)(nil),     // 4: omnipanel.sdt.v1.ConsoleCommandRequest
	(*ConsoleCommandResponse)(nil),    // 5: omnipanel.sdt.v1.ConsoleCommandResponse
	(*ConsoleLine)(nil),               // 6: omnipanel.sdt.v1.ConsoleLine
	(*Player)(nil),                    // 7: omnipanel.sdt.v1.Player
	(*PlayerList)(nil),                // 8: omnipanel.sdt.v1.PlayerList
	(*KickPlayerRequest)(nil),         // 9: omnipanel.sdt.v1.KickPlayerRequest
	(*BanPlayerRequest)(nil),          // 10: omnipanel.sdt.v1.BanPlayerRequest
	(*UnbanPlayerRequest)(nil),        // 11: omnipanel.sdt.v1.UnbanPlayerRequest
	(*TeleportPlayerRequest)(nil),     // 12: omnipanel.sdt.v1.TeleportPlayerRequest
	(*GiveItemRequest)(nil),           // 13: omnipanel.sdt.v1.GiveItemRequest
	(*WhitelistEntry)(nil),            // 14: omnipanel.sdt.v1.WhitelistEntry
	(*WhitelistResponse)(nil),         // 15: omnipanel.sdt.v1.WhitelistResponse
	(*AdminEntry)(nil),                // 16: omnipanel.sdt.v1.AdminEntry
	(*AdminList)(nil),                 // 17: omnipanel.sdt.v1.AdminList
	(*ValidationResult)(nil),          // 18: omnipanel.sdt.v1.ValidationResult
	(*BackupResponse)(nil),            // 19: omnipanel.sdt.v1.BackupResponse
	(*BackupList)(nil),                // 20: omnipanel.sdt.v1.BackupList
	(*RestoreBackupRequest)(nil),      // 21: omnipanel.sdt.v1.RestoreBackupRequest
	(*DeleteBackupRequest)(nil),       // 22: omnipanel.sdt.v1.DeleteBackupRequest
	(*ModInfo)(nil),                   // 23: omnipanel.sdt.v1.ModInfo
	(*ModList)(nil),                   // 24: omnipanel.sdt.v1.ModList
	(*InstallModRequest)(nil),         // 25: omnipanel.sdt.v1.InstallModRequest
	(*RemoveModRequest)(nil),          // 26: omnipanel.sdt.v1.RemoveModRequest
	(*ToggleModRequest)(nil),          // 27: omnipanel.sdt.v1.ToggleModRequest
	(*ServerMetrics)(nil),             // 28: omnipanel.sdt.v1.ServerMetrics
	(*v1.Empty)(nil),                  // 29: omnipanel.common.v1.Empty
	(*v1.StreamRequest)(nil),          // 30: omnipanel.common.v1.StreamRequest
	(*v1.LogEntry)(nil),               // 31: omnipanel.common.v1.LogEntry
	(*v1.StatusResponse)(nil),         // 32: omnipanel.common.v1.StatusResponse
}
var file_sdt_v1_sdt_proto_depIdxs = []int32{
	2,  // 0: omnipanel.sdt.v1.UpdateServerConfigRequest.config:type_name -> omnipanel.sdt.v1.ServerConfig
	7,  // 1: omnipanel.sdt.v1.PlayerList.players:type_name -> omnipanel.sdt.v1.Player
	14, // 2: omnipanel.sdt.v1.WhitelistResponse.entries:type_name -> omnipanel.sdt.v1.WhitelistEntry
	16, // 3: omnipanel.sdt.v1.AdminList.admins:type_name -> omnipanel.sdt.v1.AdminEntry
	19, // 4: omnipanel.sdt.v1.BackupList.backups:type_name -> omnipanel.sdt.v1.BackupResponse
	23, // 5: omnipanel.sdt.v1.ModList.mods:type_name -> omnipanel.sdt.v1.ModInfo
	0,  // 6: omnipanel.sdt.v1.SDTService.InstallServer:input_type -> omnipanel.sdt.v1.InstallServerRequest
	29, // 7: omnipanel.sdt.v1.SDTService.StartServer:input_type -> omnipanel.common.v1.Empty
	29, // 8: omnipanel.sdt.v1.SDTService.StopServer:input_type -> omnipanel.common.v1.Empty
	29, // 9: omnipanel.sdt.v1.SDTService.RestartServer:input_type -> omnipanel.common.v1.Empty
	29, // 10: omnipanel.sdt.v1.SDTService.GetServerStatus:input_type -> omnipanel.common.v1.Empty
	4,  // 11: omnipanel.sdt.v1.SDTService.SendConsoleCommand:input_type -> omnipanel.sdt.v1.ConsoleCommandRequest
	30, // 12: omnipanel.sdt.v1.SDTService.StreamConsole:input_type -> omnipanel.common.v1.StreamRequest
	29, // 13: omnipanel.sdt.v1.SDTService.GetServerConfig:input_type -> omnipanel.common.v1.Empty
	3,  // 14: omnipanel.sdt.v1.SDTService.UpdateServerConfig:input_type -> omnipanel.sdt.v1.UpdateServerConfigRequest
	29, // 15: omnipanel.sdt.v1.SDTService.ValidateConfig:input_type -> omnipanel.common.v1.Empty
	29, // 16: omnipanel.sdt.v1.SDTService.ListPlayers:input_type -> omnipanel.common.v1.Empty
	9,  // 17: omnipanel.sdt.v1.SDTService.KickPlayer:input_type -> omnipanel.sdt.v1.KickPlayerRequest
	10, // 18: omnipanel.sdt.v1.SDTService.BanPlayer:input_type -> omnipanel.sdt.v1.BanPlayerRequest
	11, // 19: omnipanel.sdt.v1.SDTService.UnbanPlayer:input_type -> omnipanel.sdt.v1.UnbanPlayerRequest
	12, // 20: omnipanel.sdt.v1.SDTService.TeleportPlayer:input_type -> omnipanel.sdt.v1.TeleportPlayerRequest
	13, // 21: omnipanel.sdt.v1.SDTService.GiveItem:input_type -> omnipanel.sdt.v1.GiveItemRequest
	29, // 22: omnipanel.sdt.v1.SDTService.ListWhitelist:input_type -> omnipanel.common.v1.Empty
	14, // 23: omnipanel.sdt.v1.SDTService.AddWhitelist:input_type -> omnipanel.sdt.v1.WhitelistEntry
	14, // 24: omnipanel.sdt.v1.SDTService.RemoveWhitelist:input_type -> omnipanel.sdt.v1.WhitelistEntry
	29, // 25: omnipanel.sdt.v1.SDTService.ListAdmins:input_type -> omnipanel.common.v1.Empty
	16, // 26: omnipanel.sdt.v1.SDTService.AddAdmin:input_type -> omnipanel.sdt.v1.AdminEntry
	16, // 27: omnipanel.sdt.v1.SDTService.RemoveAdmin:input_type -> omnipanel.sdt.v1.AdminEntry
	29, // 28: omnipanel.sdt.v1.SDTService.CreateBackup:input_type -> omnipanel.common.v1.Empty
	29, // 29: omnipanel.sdt.v1.SDTService.ListBackups:input_type -> omnipanel.common.v1.Empty
	21, // 30: omnipanel.sdt.v1.SDTService.RestoreBackup:input_type -> omnipanel.sdt.v1.RestoreBackupRequest
	22, // 31: omnipanel.sdt.v1.SDTService.DeleteBackup:input_type -> omnipanel.sdt.v1.DeleteBackupRequest
	29, // 32: omnipanel.sdt.v1.SDTService.ListMods:input_type -> omnipanel.common.v1.Empty
	25, // 33: omnipanel.sdt.v1.SDTService.InstallMod:input_type -> omnipanel.sdt.v1.InstallModRequest
	26, // 34: omnipanel.sdt.v1.SDTService.RemoveMod:input_type -> omnipanel.sdt.v1.RemoveModRequest
	27, // 35: omnipanel.sdt.v1.SDTService.ToggleMod:input_type -> omnipanel.sdt.v1.ToggleModRequest
	30, // 36: omnipanel.sdt.v1.SDTService.StreamMetrics:input_type -> omnipanel.common.v1.StreamRequest
	31, // 37: omnipanel.sdt.v1.SDTService.InstallServer:output_type -> omnipanel.common.v1.LogEntry
	32, // 38: omnipanel.sdt.v1.SDTService.StartServer:output_type -> omnipanel.common.v1.StatusResponse
	32, // 39: omnipanel.sdt.v1.SDTService.StopServer:output_type -> omnipanel.common.v1.StatusResponse
	32, // 40: omnipanel.sdt.v1.SDTService.RestartServer:output_type -> omnipanel.common.v1.StatusResponse
	1,  // 41: omnipanel.sdt.v1.SDTService.GetServerStatus:output_type -> omnipanel.sdt.v1.ServerStatusResponse
	5,  // 42: omnipanel.sdt.v1.SDTService.SendConsoleCommand:output_type -> omnipanel.sdt.v1.ConsoleCommandResponse
	6,  // 43: omnipanel.sdt.v1.SDTService.StreamConsole:output_type -> omnipanel.sdt.v1.ConsoleLine
	2,  // 44: omnipanel.sdt.v1.SDTService.GetServerConfig:output_type -> omnipanel.sdt.v1.ServerConfig
	32, // 45: omnipanel.sdt.v1.SDTService.UpdateServerConfig:output_type -> omnipanel.common.v1.StatusResponse
	18, // 46: omnipanel.sdt.v1.SDTService.ValidateConfig:output_type -> omnipanel.sdt.v1.ValidationResult
	8,  // 47: omnipanel.sdt.v1.SDTService.ListPlayers:output_type -> omnipanel.sdt.v1.PlayerList
	32, // 48: omnipanel.sdt.v1.SDTService.KickPlayer:output_type -> omnipanel.common.v1.StatusResponse
	32, // 49: omnipanel.sdt.v1.SDTService.BanPlayer:output_type -> omnipanel.common.v1.StatusResponse
	32, // 50: omnipanel.sdt.v1.SDTService.UnbanPlayer:output_type -> omnipanel.common.v1.StatusResponse
	32, // 51: omnipanel.sdt.v1.SDTService.TeleportPlayer:output_type -> omnipanel.common.v1.StatusResponse
	32, // 52: omnipanel.sdt.v1.SDTService.GiveItem:output_type -> omnipanel.common.v1.StatusResponse
	15, // 53: omnipanel.sdt.v1.SDTService.ListWhitelist:output_type -> omnipanel.sdt.v1.WhitelistResponse
	32, // 54: omnipanel.sdt.v1.SDTService.AddWhitelist:output_type -> omnipanel.common.v1.StatusResponse
	32, // 55: omnipanel.sdt.v1.SDTService.RemoveWhitelist:output_type -> omnipanel.common.v1.StatusResponse
	17, // 56: omnipanel.sdt.v1.SDTService.ListAdmins:output_type -> omnipanel.sdt.v1.AdminList
	32, // 57: omnipanel.sdt.v1.SDTService.AddAdmin:output_type -> omnipanel.common.v1.StatusResponse
	32, // 58: omnipanel.sdt.v1.SDTService.RemoveAdmin:output_type -> omnipanel.common.v1.StatusResponse
	19, // 59: omnipanel.sdt.v1.SDTService.CreateBackup:output_type -> omnipanel.sdt.v1.BackupResponse
	20, // 60: omnipanel.sdt.v1.SDTService.ListBackups:output_type -> omnipanel.sdt.v1.BackupList
	32, // 61: omnipanel.sdt.v1.SDTService.RestoreBackup:output_type -> omnipanel.common.v1.StatusResponse
	32, // 62: omnipanel.sdt.v1.SDTService.DeleteBackup:output_type -> omnipanel.common.v1.StatusResponse
	24, // 63: omnipanel.sdt.v1.SDTService.ListMods:output_type -> omnipanel.sdt.v1.ModList
	32, // 64: omnipanel.sdt.v1.SDTService.InstallMod:output_type -> omnipanel.common.v1.StatusResponse
	32, // 65: omnipanel.sdt.v1.SDTService.RemoveMod:output_type -> omnipanel.common.v1.StatusResponse
	32, // 66: omnipanel.sdt.v1.SDTService.ToggleMod:output_type -> omnipanel.common.v1.StatusResponse
	28, // 67: omnipanel.sdt.v1.SDTService.StreamMetrics:output_type -> omnipanel.sdt.v1.ServerMetrics
	37, // [37:68] is the sub-list for method output_type
	6,  // [6:37] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sdt_v1_sdt_proto_init() }
func file_sdt_v1_sdt_proto_init() {
	if File_sdt_v1_sdt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdt_v1_sdt_proto_rawDesc), len(file_sdt_v1_sdt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sdt_v1_sdt_proto_goTypes,
		DependencyIndexes: file_sdt_v1_sdt_proto_depIdxs,
		MessageInfos:      file_sdt_v1_sdt_proto_msgTypes,
	}.Build()
	File_sdt_v1_sdt_proto = out.File
	file_sdt_v1_sdt_proto_goTypes = nil
	file_sdt_v1_sdt_proto_depIdxs = nil
}
