// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: sdt/v1/sdt.proto

package sdtv1

import (
	context "context"
	v1 "github.com/omnipanel/omnipanel/proto/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SDTService_InstallServer_FullMethodName      = "/omnipanel.sdt.v1.SDTService/InstallServer"
	SDTService_StartServer_FullMethodName        = "/omnipanel.sdt.v1.SDTService/StartServer"
	SDTService_StopServer_FullMethodName         = "/omnipanel.sdt.v1.SDTService/StopServer"
	SDTService_RestartServer_FullMethodName      = "/omnipanel.sdt.v1.SDTService/RestartServer"
	SDTService_GetServerStatus_FullMethodName    = "/omnipanel.sdt.v1.SDTService/GetServerStatus"
	SDTService_SendConsoleCommand_FullMethodName = "/omnipanel.sdt.v1.SDTService/SendConsoleCommand"
	SDTService_StreamConsole_FullMethodName      = "/omnipanel.sdt.v1.SDTService/StreamConsole"
	SDTService_GetServerConfig_FullMethodName    = "/omnipanel.sdt.v1.SDTService/GetServerConfig"
	SDTService_UpdateServerConfig_FullMethodName = "/omnipanel.sdt.v1.SDTService/UpdateServerConfig"
	SDTService_ValidateConfig_FullMethodName     = "/omnipanel.sdt.v1.SDTService/ValidateConfig"
	SDTService_ListPlayers_FullMethodName        = "/omnipanel.sdt.v1.SDTService/ListPlayers"
	SDTService_KickPlayer_FullMethodName         = "/omnipanel.sdt.v1.SDTService/KickPlayer"
	SDTService_BanPlayer_FullMethodName          = "/omnipanel.sdt.v1.SDTService/BanPlayer"
	SDTService_UnbanPlayer_FullMethodName        = "/omnipanel.sdt.v1.SDTService/UnbanPlayer"
	SDTService_TeleportPlayer_FullMethodName     = "/omnipanel.sdt.v1.SDTService/TeleportPlayer"
	SDTService_GiveItem_FullMethodName           = "/omnipanel.sdt.v1.SDTService/GiveItem"
	SDTService_ListWhitelist_FullMethodName      = "/omnipanel.sdt.v1.SDTService/ListWhitelist"
	SDTService_AddWhitelist_FullMethodName       = "/omnipanel.sdt.v1.SDTService/AddWhitelist"
	SDTService_RemoveWhitelist_FullMethodName    = "/omnipanel.sdt.v1.SDTService/RemoveWhitelist"
	SDTService_ListAdmins_FullMethodName         = "/omnipanel.sdt.v1.SDTService/ListAdmins"
	SDTService_AddAdmin_FullMethodName           = "/omnipanel.sdt.v1.SDTService/AddAdmin"
	SDTService_RemoveAdmin_FullMethodName        = "/omnipanel.sdt.v1.SDTService/RemoveAdmin"
	SDTService_CreateBackup_FullMethodName       = "/omnipanel.sdt.v1.SDTService/CreateBackup"
	SDTService_ListBackups_FullMethodName        = "/omnipanel.sdt.v1.SDTService/ListBackups"
	SDTService_RestoreBackup_FullMethodName      = "/omnipanel.sdt.v1.SDTService/RestoreBackup"
	SDTService_DeleteBackup_FullMethodName       = "/omnipanel.sdt.v1.SDTService/DeleteBackup"
	SDTService_ListMods_FullMethodName           = "/omnipanel.sdt.v1.SDTService/ListMods"
	SDTService_InstallMod_FullMethodName         = "/omnipanel.sdt.v1.SDTService/InstallMod"
	SDTService_RemoveMod_FullMethodName          = "/omnipanel.sdt.v1.SDTService/RemoveMod"
	SDTService_ToggleMod_FullMethodName          = "/omnipanel.sdt.v1.SDTService/ToggleMod"
	SDTService_StreamMetrics_FullMethodName      = "/omnipanel.sdt.v1.SDTService/StreamMetrics"
)

// SDTServiceClient is the client API for SDTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SDTServiceClient interface {
	// ---------- 服务端生命周期 ----------
	InstallServer(ctx context.Context, in *InstallServerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.LogEntry], error)
	StartServer(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	StopServer(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	RestartServer(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	GetServerStatus(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*ServerStatusResponse, error)
	// ---------- 控制台 ----------
	SendConsoleCommand(ctx context.Context, in *ConsoleCommandRequest, opts ...grpc.CallOption) (*ConsoleCommandResponse, error)
	StreamConsole(ctx context.Context, in *v1.StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleLine], error)
	// ---------- 配置文件 CRUD ----------
	GetServerConfig(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*ServerConfig, error)
	UpdateServerConfig(ctx context.Context, in *UpdateServerConfigRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	ValidateConfig(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*ValidationResult, error)
	// ---------- 玩家管理 ----------
	ListPlayers(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*PlayerList, error)
	KickPlayer(ctx context.Context, in *KickPlayerRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	BanPlayer(ctx context.Context, in *BanPlayerRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	UnbanPlayer(ctx context.Context, in *UnbanPlayerRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	TeleportPlayer(ctx context.Context, in *TeleportPlayerRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	GiveItem(ctx context.Context, in *GiveItemRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	// ---------- 白名单 ----------
	ListWhitelist(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*WhitelistResponse, error)
	AddWhitelist(ctx context.Context, in *WhitelistEntry, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	RemoveWhitelist(ctx context.Context, in *WhitelistEntry, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	// ---------- 管理员 ----------
	ListAdmins(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*AdminList, error)
	AddAdmin(ctx context.Context, in *AdminEntry, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	RemoveAdmin(ctx context.Context, in *AdminEntry, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	// ---------- 存档备份 ----------
	CreateBackup(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*BackupResponse, error)
	ListBackups(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*BackupList, error)
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	// ---------- MOD 管理 ----------
	ListMods(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*ModList, error)
	InstallMod(ctx context.Context, in *InstallModRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	RemoveMod(ctx context.Context, in *RemoveModRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	ToggleMod(ctx context.Context, in *ToggleModRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error)
	// ---------- 实时监控 ----------
	StreamMetrics(ctx context.Context, in *v1.StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerMetrics], error)
}

type sDTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSDTServiceClient(cc grpc.ClientConnInterface) SDTServiceClient {
	return &sDTServiceClient{cc}
}

func (c *sDTServiceClient) InstallServer(ctx context.Context, in *InstallServerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[v1.LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SDTService_ServiceDesc.Streams[0], SDTService_InstallServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstallServerRequest, v1.LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDTService_InstallServerClient = grpc.ServerStreamingClient[v1.LogEntry]

func (c *sDTServiceClient) StartServer(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_StartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) StopServer(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_StopServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) RestartServer(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_RestartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) GetServerStatus(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*ServerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerStatusResponse)
	err := c.cc.Invoke(ctx, SDTService_GetServerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) SendConsoleCommand(ctx context.Context, in *ConsoleCommandRequest, opts ...grpc.CallOption) (*ConsoleCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsoleCommandResponse)
	err := c.cc.Invoke(ctx, SDTService_SendConsoleCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) StreamConsole(ctx context.Context, in *v1.StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsoleLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SDTService_ServiceDesc.Streams[1], SDTService_StreamConsole_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v1.StreamRequest, ConsoleLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDTService_StreamConsoleClient = grpc.ServerStreamingClient[ConsoleLine]

func (c *sDTServiceClient) GetServerConfig(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*ServerConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerConfig)
	err := c.cc.Invoke(ctx, SDTService_GetServerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) UpdateServerConfig(ctx context.Context, in *UpdateServerConfigRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_UpdateServerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) ValidateConfig(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, SDTService_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) ListPlayers(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*PlayerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerList)
	err := c.cc.Invoke(ctx, SDTService_ListPlayers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) KickPlayer(ctx context.Context, in *KickPlayerRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_KickPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) BanPlayer(ctx context.Context, in *BanPlayerRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_BanPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) UnbanPlayer(ctx context.Context, in *UnbanPlayerRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_UnbanPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) TeleportPlayer(ctx context.Context, in *TeleportPlayerRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_TeleportPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) GiveItem(ctx context.Context, in *GiveItemRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_GiveItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) ListWhitelist(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*WhitelistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhitelistResponse)
	err := c.cc.Invoke(ctx, SDTService_ListWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) AddWhitelist(ctx context.Context, in *WhitelistEntry, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_AddWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) RemoveWhitelist(ctx context.Context, in *WhitelistEntry, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_RemoveWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) ListAdmins(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*AdminList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminList)
	err := c.cc.Invoke(ctx, SDTService_ListAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) AddAdmin(ctx context.Context, in *AdminEntry, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_AddAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) RemoveAdmin(ctx context.Context, in *AdminEntry, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_RemoveAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) CreateBackup(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*BackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, SDTService_CreateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) ListBackups(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*BackupList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupList)
	err := c.cc.Invoke(ctx, SDTService_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_RestoreBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_DeleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) ListMods(ctx context.Context, in *v1.Empty, opts ...grpc.CallOption) (*ModList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModList)
	err := c.cc.Invoke(ctx, SDTService_ListMods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) InstallMod(ctx context.Context, in *InstallModRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_InstallMod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) RemoveMod(ctx context.Context, in *RemoveModRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_RemoveMod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) ToggleMod(ctx context.Context, in *ToggleModRequest, opts ...grpc.CallOption) (*v1.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.StatusResponse)
	err := c.cc.Invoke(ctx, SDTService_ToggleMod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDTServiceClient) StreamMetrics(ctx context.Context, in *v1.StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerMetrics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SDTService_ServiceDesc.Streams[2], SDTService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v1.StreamRequest, ServerMetrics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDTService_StreamMetricsClient = grpc.ServerStreamingClient[ServerMetrics]

// SDTServiceServer is the server API for SDTService service.
// All implementations must embed UnimplementedSDTServiceServer
// for forward compatibility.
type SDTServiceServer interface {
	// ---------- 服务端生命周期 ----------
	InstallServer(*InstallServerRequest, grpc.ServerStreamingServer[v1.LogEntry]) error
	StartServer(context.Context, *v1.Empty) (*v1.StatusResponse, error)
	StopServer(context.Context, *v1.Empty) (*v1.StatusResponse, error)
	RestartServer(context.Context, *v1.Empty) (*v1.StatusResponse, error)
	GetServerStatus(context.Context, *v1.Empty) (*ServerStatusResponse, error)
	// ---------- 控制台 ----------
	SendConsoleCommand(context.Context, *ConsoleCommandRequest) (*ConsoleCommandResponse, error)
	StreamConsole(*v1.StreamRequest, grpc.ServerStreamingServer[ConsoleLine]) error
	// ---------- 配置文件 CRUD ----------
	GetServerConfig(context.Context, *v1.Empty) (*ServerConfig, error)
	UpdateServerConfig(context.Context, *UpdateServerConfigRequest) (*v1.StatusResponse, error)
	ValidateConfig(context.Context, *v1.Empty) (*ValidationResult, error)
	// ---------- 玩家管理 ----------
	ListPlayers(context.Context, *v1.Empty) (*PlayerList, error)
	KickPlayer(context.Context, *KickPlayerRequest) (*v1.StatusResponse, error)
	BanPlayer(context.Context, *BanPlayerRequest) (*v1.StatusResponse, error)
	UnbanPlayer(context.Context, *UnbanPlayerRequest) (*v1.StatusResponse, error)
	TeleportPlayer(context.Context, *TeleportPlayerRequest) (*v1.StatusResponse, error)
	GiveItem(context.Context, *GiveItemRequest) (*v1.StatusResponse, error)
	// ---------- 白名单 ----------
	ListWhitelist(context.Context, *v1.Empty) (*WhitelistResponse, error)
	AddWhitelist(context.Context, *WhitelistEntry) (*v1.StatusResponse, error)
	RemoveWhitelist(context.Context, *WhitelistEntry) (*v1.StatusResponse, error)
	// ---------- 管理员 ----------
	ListAdmins(context.Context, *v1.Empty) (*AdminList, error)
	AddAdmin(context.Context, *AdminEntry) (*v1.StatusResponse, error)
	RemoveAdmin(context.Context, *AdminEntry) (*v1.StatusResponse, error)
	// ---------- 存档备份 ----------
	CreateBackup(context.Context, *v1.Empty) (*BackupResponse, error)
	ListBackups(context.Context, *v1.Empty) (*BackupList, error)
	RestoreBackup(context.Context, *RestoreBackupRequest) (*v1.StatusResponse, error)
	DeleteBackup(context.Context, *DeleteBackupRequest) (*v1.StatusResponse, error)
	// ---------- MOD 管理 ----------
	ListMods(context.Context, *v1.Empty) (*ModList, error)
	InstallMod(context.Context, *InstallModRequest) (*v1.StatusResponse, error)
	RemoveMod(context.Context, *RemoveModRequest) (*v1.StatusResponse, error)
	ToggleMod(context.Context, *ToggleModRequest) (*v1.StatusResponse, error)
	// ---------- 实时监控 ----------
	StreamMetrics(*v1.StreamRequest, grpc.ServerStreamingServer[ServerMetrics]) error
	mustEmbedUnimplementedSDTServiceServer()
}

// UnimplementedSDTServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSDTServiceServer struct{}

func (UnimplementedSDTServiceServer) InstallServer(*InstallServerRequest, grpc.ServerStreamingServer[v1.LogEntry]) error {
	return status.Error(codes.Unimplemented, "method InstallServer not implemented")
}
func (UnimplementedSDTServiceServer) StartServer(context.Context, *v1.Empty) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartServer not implemented")
}
func (UnimplementedSDTServiceServer) StopServer(context.Context, *v1.Empty) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopServer not implemented")
}
func (UnimplementedSDTServiceServer) RestartServer(context.Context, *v1.Empty) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartServer not implemented")
}
func (UnimplementedSDTServiceServer) GetServerStatus(context.Context, *v1.Empty) (*ServerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedSDTServiceServer) SendConsoleCommand(context.Context, *ConsoleCommandRequest) (*ConsoleCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendConsoleCommand not implemented")
}
func (UnimplementedSDTServiceServer) StreamConsole(*v1.StreamRequest, grpc.ServerStreamingServer[ConsoleLine]) error {
	return status.Error(codes.Unimplemented, "method StreamConsole not implemented")
}
func (UnimplementedSDTServiceServer) GetServerConfig(context.Context, *v1.Empty) (*ServerConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerConfig not implemented")
}
func (UnimplementedSDTServiceServer) UpdateServerConfig(context.Context, *UpdateServerConfigRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateServerConfig not implemented")
}
func (UnimplementedSDTServiceServer) ValidateConfig(context.Context, *v1.Empty) (*ValidationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedSDTServiceServer) ListPlayers(context.Context, *v1.Empty) (*PlayerList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlayers not implemented")
}
func (UnimplementedSDTServiceServer) KickPlayer(context.Context, *KickPlayerRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KickPlayer not implemented")
}
func (UnimplementedSDTServiceServer) BanPlayer(context.Context, *BanPlayerRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BanPlayer not implemented")
}
func (UnimplementedSDTServiceServer) UnbanPlayer(context.Context, *UnbanPlayerRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbanPlayer not implemented")
}
func (UnimplementedSDTServiceServer) TeleportPlayer(context.Context, *TeleportPlayerRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TeleportPlayer not implemented")
}
func (UnimplementedSDTServiceServer) GiveItem(context.Context, *GiveItemRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GiveItem not implemented")
}
func (UnimplementedSDTServiceServer) ListWhitelist(context.Context, *v1.Empty) (*WhitelistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWhitelist not implemented")
}
func (UnimplementedSDTServiceServer) AddWhitelist(context.Context, *WhitelistEntry) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWhitelist not implemented")
}
func (UnimplementedSDTServiceServer) RemoveWhitelist(context.Context, *WhitelistEntry) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWhitelist not implemented")
}
func (UnimplementedSDTServiceServer) ListAdmins(context.Context, *v1.Empty) (*AdminList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdmins not implemented")
}
func (UnimplementedSDTServiceServer) AddAdmin(context.Context, *AdminEntry) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAdmin not implemented")
}
func (UnimplementedSDTServiceServer) RemoveAdmin(context.Context, *AdminEntry) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAdmin not implemented")
}
func (UnimplementedSDTServiceServer) CreateBackup(context.Context, *v1.Empty) (*BackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedSDTServiceServer) ListBackups(context.Context, *v1.Empty) (*BackupList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedSDTServiceServer) RestoreBackup(context.Context, *RestoreBackupRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (UnimplementedSDTServiceServer) DeleteBackup(context.Context, *DeleteBackupRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedSDTServiceServer) ListMods(context.Context, *v1.Empty) (*ModList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMods not implemented")
}
func (UnimplementedSDTServiceServer) InstallMod(context.Context, *InstallModRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallMod not implemented")
}
func (UnimplementedSDTServiceServer) RemoveMod(context.Context, *RemoveModRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMod not implemented")
}
func (UnimplementedSDTServiceServer) ToggleMod(context.Context, *ToggleModRequest) (*v1.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleMod not implemented")
}
func (UnimplementedSDTServiceServer) StreamMetrics(*v1.StreamRequest, grpc.ServerStreamingServer[ServerMetrics]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedSDTServiceServer) mustEmbedUnimplementedSDTServiceServer() {}
func (UnimplementedSDTServiceServer) testEmbeddedByValue()                    {}

// UnsafeSDTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SDTServiceServer will
// result in compilation errors.
type UnsafeSDTServiceServer interface {
	mustEmbedUnimplementedSDTServiceServer()
}

func RegisterSDTServiceServer(s grpc.ServiceRegistrar, srv SDTServiceServer) {
	// If the following call panics, it indicates UnimplementedSDTServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SDTService_ServiceDesc, srv)
}

func _SDTService_InstallServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstallServerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SDTServiceServer).InstallServer(m, &grpc.GenericServerStream[InstallServerRequest, v1.LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDTService_InstallServerServer = grpc.ServerStreamingServer[v1.LogEntry]

func _SDTService_StartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).StartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_StartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).StartServer(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_StopServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).StopServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_StopServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).StopServer(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_RestartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).RestartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_RestartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).RestartServer(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_GetServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).GetServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_GetServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).GetServerStatus(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_SendConsoleCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsoleCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).SendConsoleCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_SendConsoleCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).SendConsoleCommand(ctx, req.(*ConsoleCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_StreamConsole_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(v1.StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SDTServiceServer).StreamConsole(m, &grpc.GenericServerStream[v1.StreamRequest, ConsoleLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDTService_StreamConsoleServer = grpc.ServerStreamingServer[ConsoleLine]

func _SDTService_GetServerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).GetServerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_GetServerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).GetServerConfig(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_UpdateServerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).UpdateServerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_UpdateServerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).UpdateServerConfig(ctx, req.(*UpdateServerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).ValidateConfig(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_ListPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).ListPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_ListPlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).ListPlayers(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_KickPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).KickPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_KickPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).KickPlayer(ctx, req.(*KickPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_BanPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).BanPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_BanPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).BanPlayer(ctx, req.(*BanPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_UnbanPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).UnbanPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_UnbanPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).UnbanPlayer(ctx, req.(*UnbanPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_TeleportPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeleportPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).TeleportPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_TeleportPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).TeleportPlayer(ctx, req.(*TeleportPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_GiveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GiveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).GiveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_GiveItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).GiveItem(ctx, req.(*GiveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_ListWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).ListWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_ListWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).ListWhitelist(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_AddWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhitelistEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).AddWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_AddWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).AddWhitelist(ctx, req.(*WhitelistEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_RemoveWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhitelistEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).RemoveWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_RemoveWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).RemoveWhitelist(ctx, req.(*WhitelistEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_ListAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).ListAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_ListAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).ListAdmins(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_AddAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).AddAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_AddAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).AddAdmin(ctx, req.(*AdminEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_RemoveAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).RemoveAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_RemoveAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).RemoveAdmin(ctx, req.(*AdminEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_CreateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).CreateBackup(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).ListBackups(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_RestoreBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_DeleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_ListMods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).ListMods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_ListMods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).ListMods(ctx, req.(*v1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_InstallMod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallModRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).InstallMod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_InstallMod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).InstallMod(ctx, req.(*InstallModRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_RemoveMod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveModRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).RemoveMod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_RemoveMod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).RemoveMod(ctx, req.(*RemoveModRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_ToggleMod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleModRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDTServiceServer).ToggleMod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDTService_ToggleMod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDTServiceServer).ToggleMod(ctx, req.(*ToggleModRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDTService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(v1.StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SDTServiceServer).StreamMetrics(m, &grpc.GenericServerStream[v1.StreamRequest, ServerMetrics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SDTService_StreamMetricsServer = grpc.ServerStreamingServer[ServerMetrics]

// SDTService_ServiceDesc is the grpc.ServiceDesc for SDTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SDTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omnipanel.sdt.v1.SDTService",
	HandlerType: (*SDTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartServer",
			Handler:    _SDTService_StartServer_Handler,
		},
		{
			MethodName: "StopServer",
			Handler:    _SDTService_StopServer_Handler,
		},
		{
			MethodName: "RestartServer",
			Handler:    _SDTService_RestartServer_Handler,
		},
		{
			MethodName: "GetServerStatus",
			Handler:    _SDTService_GetServerStatus_Handler,
		},
		{
			MethodName: "SendConsoleCommand",
			Handler:    _SDTService_SendConsoleCommand_Handler,
		},
		{
			MethodName: "GetServerConfig",
			Handler:    _SDTService_GetServerConfig_Handler,
		},
		{
			MethodName: "UpdateServerConfig",
			Handler:    _SDTService_UpdateServerConfig_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _SDTService_ValidateConfig_Handler,
		},
		{
			MethodName: "ListPlayers",
			Handler:    _SDTService_ListPlayers_Handler,
		},
		{
			MethodName: "KickPlayer",
			Handler:    _SDTService_KickPlayer_Handler,
		},
		{
			MethodName: "BanPlayer",
			Handler:    _SDTService_BanPlayer_Handler,
		},
		{
			MethodName: "UnbanPlayer",
			Handler:    _SDTService_UnbanPlayer_Handler,
		},
		{
			MethodName: "TeleportPlayer",
			Handler:    _SDTService_TeleportPlayer_Handler,
		},
		{
			MethodName: "GiveItem",
			Handler:    _SDTService_GiveItem_Handler,
		},
		{
			MethodName: "ListWhitelist",
			Handler:    _SDTService_ListWhitelist_Handler,
		},
		{
			MethodName: "AddWhitelist",
			Handler:    _SDTService_AddWhitelist_Handler,
		},
		{
			MethodName: "RemoveWhitelist",
			Handler:    _SDTService_RemoveWhitelist_Handler,
		},
		{
			MethodName: "ListAdmins",
			Handler:    _SDTService_ListAdmins_Handler,
		},
		{
			MethodName: "AddAdmin",
			Handler:    _SDTService_AddAdmin_Handler,
		},
		{
			MethodName: "RemoveAdmin",
			Handler:    _SDTService_RemoveAdmin_Handler,
		},
		{
			MethodName: "CreateBackup",
			Handler:    _SDTService_CreateBackup_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _SDTService_ListBackups_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _SDTService_RestoreBackup_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _SDTService_DeleteBackup_Handler,
		},
		{
			MethodName: "ListMods",
			Handler:    _SDTService_ListMods_Handler,
		},
		{
			MethodName: "InstallMod",
			Handler:    _SDTService_InstallMod_Handler,
		},
		{
			MethodName: "RemoveMod",
			Handler:    _SDTService_RemoveMod_Handler,
		},
		{
			MethodName: "ToggleMod",
			Handler:    _SDTService_ToggleMod_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InstallServer",
			Handler:       _SDTService_InstallServer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamConsole",
			Handler:       _SDTService_StreamConsole_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMetrics",
			Handler:       _SDTService_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdt/v1/sdt.proto",
}
